# Generated by Django 3.2 on 2021-05-20 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_rename_image_photo_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='image',
        ),
    ]
